=== Matthew-npp/ZJ-XML-XSD-XSL/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="vojeske_vybaveni">
<xs:complexType>
<xs:sequence>
  <xs:element name="pusky" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>    
      <xs:sequence>
        <xs:element name="oznaceni_pusky" type="xs:string"/>
        <xs:element name="vyvinuto" type="roky"/>
        <xs:element name="kalibr" type="xs:string"/>
        <xs:element name="zasobnik" type="xs:integer"/>
        <xs:element name="cena" type="xs:integer"/>
        <xs:element name="vynalezce" type="xs:string"/>
        <xs:element name="urceni" type="xs:string"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="kategorie" use="optional"/>
      <xs:attribute type="xs:string" name="vyrobce" use="optional"/>      
    </xs:complexType>
  </xs:element>

<xs:element name="noze" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>    
      <xs:sequence>
        <xs:element name="nazev" type="xs:string"/>
        <xs:element name="material" type="xs:string"/>
        <xs:element name="delka_cepele" type="xs:integer"/>        
      </xs:sequence>
      <xs:attribute type="xs:string" name="kategorie" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="lode" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>    
      <xs:sequence>
        <xs:element name="uvedeni_do_provozu" type="roky"/>
        <xs:element name="vytlak" type="xs:integer"/>       
      </xs:sequence>
      <xs:attribute type="xs:string" name="kategorie" use="optional"/>
      <xs:attribute type="xs:string" name="typ" use="optional"/>
      <xs:attribute type="xs:string" name="kodove_oznaceni" use="optional"/>      
    </xs:complexType>
  </xs:element>

  <xs:element name="tank" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>        
      <xs:sequence>
        <xs:element name="oznaceni_tanku" type="xs:string"/>
        <xs:element name="palivo" type="palivo"/>
        <xs:element name="delo" type="xs:integer"/>
        <xs:element name="rok_vyroby" type="roky"/>
        <xs:element name="vaha" type="xs:string"/>
        <xs:element name="posadka" type="posadka"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="kategorie" use="optional"/>    
      <xs:attribute type="xs:string" name="zeme" use="optional"/>        
    </xs:complexType>
  </xs:element>

  </xs:sequence>
  </xs:complexType>
 </xs:element> 

 <xs:simpleType name="roky">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1900"/>
    <xs:maxInclusive value="2022"/>
  </xs:restriction>
</xs:simpleType>

 <xs:simpleType name="palivo">
  <xs:restriction base="xs:string">
    <xs:enumeration value="benzÃ­n"/>
    <xs:enumeration value="plyn"/>
    <xs:enumeration value="nafta"/>
  </xs:restriction>
</xs:simpleType>

 <xs:simpleType name="posadka">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
    <xs:maxInclusive value="10"/>
  </xs:restriction>
</xs:simpleType>
</xs:schema>

=== Matthew-npp/ZJ-XML-XSD-XSL/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transformace.xsl"?>
<vojeske_vybaveni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
 
<pusky kategorie="Pušky" vyrobce="Knight's Armament Company">    
    <oznaceni_pusky>SR-25</oznaceni_pusky>
    <vyvinuto>1990</vyvinuto>
    <kalibr>7.62x51</kalibr>
    <zasobnik>20</zasobnik>
    <cena>122500</cena> 
    <vynalezce>Eugene Stoner</vynalezce> 
    <urceni>Odtřelovací</urceni> 
</pusky>

<pusky kategorie="Pušky" vyrobce="Heckler Koch">    
    <oznaceni_pusky>MP5</oznaceni_pusky>
    <vyvinuto>1966</vyvinuto>
    <kalibr>9mm</kalibr>
    <zasobnik>30</zasobnik>
    <cena>65000</cena> 
    <vynalezce>Tilo Möller</vynalezce> 
    <urceni>Samopal</urceni> 
</pusky>

<pusky kategorie="Pušky" vyrobce="Kalashnikov Concern">    
    <oznaceni_pusky>AK-12</oznaceni_pusky>
    <vyvinuto>2011</vyvinuto>
    <kalibr>5.46x39mm</kalibr>
    <zasobnik>30</zasobnik>
    <cena>27000</cena> 
    <vynalezce>Mikhail Kalashnikov</vynalezce> 
    <urceni>Bojová puška</urceni> 
</pusky>
 
 <pusky kategorie="Pušky" vyrobce="Tula Arms Plant">    
    <oznaceni_pusky>VSS Vintorez</oznaceni_pusky>
    <vyvinuto>1980</vyvinuto>
    <kalibr>9x39mm</kalibr>
    <zasobnik>20</zasobnik>
    <cena>66000</cena> 
    <vynalezce>Vladimir Krasnikov</vynalezce> 
    <urceni>Odstřelovací puška</urceni> 
</pusky>

<noze kategorie="Nože" >
    <nazev>Mikov Uton 362</nazev>
    <material>nerez. ocel</material>
    <delka_cepele>14</delka_cepele>    
</noze> 


<lode kategorie="Lodě" typ="letadlova" kodove_oznaceni="USS Enterprise CV-6">
    <uvedeni_do_provozu>1939</uvedeni_do_provozu>
    <vytlak>25500</vytlak> 
</lode> 
<lode kategorie="Lodě" typ="bitevní" kodove_oznaceni="Třída Iowa">
    <uvedeni_do_provozu>1943</uvedeni_do_provozu>
    <vytlak>45000</vytlak> 
</lode> 

<tank kategorie="Tanky" zeme="USA">
    <oznaceni_tanku>M4 Sherman</oznaceni_tanku>
    <palivo>benzín</palivo>
    <delo>75</delo>
    <rok_vyroby>1941</rok_vyroby>
    <vaha>30 T</vaha>
    <posadka>5</posadka>
</tank> 

<tank kategorie="Tanky" zeme="Německo">
    <oznaceni_tanku>Panzerkampfwagen VI Tiger</oznaceni_tanku>
    <palivo>benzín</palivo>
    <delo>88</delo>
    <rok_vyroby>1942</rok_vyroby>
    <vaha>57 T</vaha>
    <posadka>5</posadka>
</tank> 

<tank kategorie="Tanky" zeme="USA">
    <oznaceni_tanku>M1 Abrams</oznaceni_tanku>
    <palivo>plyn</palivo>
    <delo>105</delo>
    <rok_vyroby>1996</rok_vyroby>
    <vaha>63 T</vaha>
    <posadka>4</posadka>
</tank> 

</vojeske_vybaveni>
